### ISSUE TITLE
Adopt Manifest v3 for Chrome

### ISSUE THREAD

**Issue by sambacha** [odacavo/enhanced-iframe-protection#1]
Google deprecated v2 extension manifests on January 1st. You must use v3 manifests in order to publish after this date.

Thanks for this extension!

**Comment by MalwareCube** [comment]
Correct! Thanks for this. I have tested manifest v3 and will update the repo shortly.

**Comment by sambacha** [comment]
> Correct! Thanks for this. I have tested manifest v3 and will update the repo shortly.

Also, do you have test cases / would you want some test cases? iframe hijacking is of concern to me wrt end users utilizing chrome extensions like metamask / portis (these are ethereum/web3 wallet providers that use iframe) . Currently wallet providers like metamask are using heuristic based methods for determining likely phishing attempts, see https://github.com/MetaMask/eth-phishing-detect. 

Cheers and thanks for the informative project!

**Comment by MalwareCube** [comment]
Chrome manifest has been updated. Thanks again! 

I currently do not have test cases other than against the Browser-In-The-Browser templates released by mrd0x https://github.com/mrd0x/BITB

I have not had much experience with Metamask / portis but I'm aware of some of the phishing attacks against crypto wallets. I definitely think this could be a great use case for this extension and definitely some research could be done.

**Comment by sambacha** [comment]
> Chrome manifest has been updated. Thanks again!
> 
> I currently do not have test cases other than against the Browser-In-The-Browser templates released by mrd0x [mrd0x/BITB](https://github.com/mrd0x/BITB)
> 
> I have not had much experience with Metamask / portis but I'm aware of some of the phishing attacks against crypto wallets. I definitely think this could be a great use case for this extension and definitely some research could be done.

What is the best way to contact you? Email is not readily available anywhere on first pass. Would want to do a grant for this if that is of interest to you, either way thanks for providing a mitigation solution

**Comment by MalwareCube** [comment]
Sure, you can reach me here: odacavo@protonmail.com

I will close the issue as the manifest has been updated. Thanks again.
