### ISSUE TITLE
Technical question about JS

### ISSUE THREAD

**Issue by burtek** [odacavo/enhanced-iframe-protection#3]
https://github.com/odacavo/enhanced-iframe-protection/blob/5d03784777f2bce61d208be643e4d10bce338430/chrome-api/src/content.js#L222-L224

Out of curiosity, what's the line 222 for? In JS this would copy reference, not do a shallow copy of an array, so pushing value to `ddcopy` on line 223 will mutate the `srcAllowResultP` array as well...

**Comment by MalwareCube** [comment]
I think it was supposed to be a shallow copy but ended up not being needed. Feel free to submit a pull request instead.
