### ISSUE TITLE
Ambiguous warning banner button

### ISSUE THREAD

**Issue by burtek** [odacavo/enhanced-iframe-protection#4]
![image](https://user-images.githubusercontent.com/2940958/161431630-4c121b17-fbf6-4ce5-9e9e-49c740fb99a7.png)

What URL does the right button add to whitelist? Is it the parent domain or the frame domain? It's not really clear from the text.

**Comment by MalwareCube** [comment]
If you hover over the button, it will give you the domain of the parent site that will be whitelisted. Ex: `pinterest.ca`

![image](https://user-images.githubusercontent.com/31866708/161431838-1edb9a21-0259-4db4-9893-06eced27f7d9.png)
