### ISSUE TITLE
Brilliant extension - made a feature request to Mozilla

### ISSUE THREAD

**Issue by Am0rphous** [odacavo/enhanced-iframe-protection#6]
Hi @odacavo
Brilliant extension. I think this should be implemented in the Mozilla browser, so I made a feature request to Mozilla. One can look at it on [this link](https://connect.mozilla.org/t5/ideas/display-a-warning-in-the-browser-when-detecting-iframes/idi-p/8397).

Best regards
-

Edit: Fixed the link so its correct :)

**Comment by MalwareCube** [comment]
That's awesome! Thank you for submitting that as a Mozilla req @Am0rphous

**Comment by Am0rphous** [comment]
You're welcome!

The link seems broken, but it's working when logging into connect.mozilla.org. Cheers!
