### ISSUE TITLE
Add widget or button in toolbar like other exensions to disable for a domain, instead never show warnings for this site

### ISSUE THREAD

**Issue by sdykae** [odacavo/enhanced-iframe-protection#8]
200 and more iframes here https://builder.io/fiddle/fb98adf93ad5467180329fdaa9711f27
can't close for all warnings

**Comment by sdykae** [comment]
could be like vimium extension

**Comment by MalwareCube** [comment]
![image](https://user-images.githubusercontent.com/31866708/181620192-b4f1b266-61af-407c-9136-af9018370361.png)
This functionality exists currently, clicking "Never Show Warnings On This Site" will add the domain to an allow-list via local storage. That domain will now have the extension disabled. It just requires a refresh for single-page / javascript driven sites.

**Comment by sdykae** [comment]
Functionality does not work when there are lots of iframes, like 200, and you have to click it 200 times or more.

**Comment by MalwareCube** [comment]
Ah. The site/editor you have linked appears to be blocking you from interacting with or clicking on the warning message. For example, if you navigate to https://builder.io/login and click "Never Show Warnings On This Site", it should fix it on the URL you linked. 

That is an issue of itself, and a toolbar popup would fix that, however I am not actively updating the project at this time. I will leave the issue open to accept PRs for this functionality.

Thanks for bringing it up.
