### ISSUE TITLE
Why would a BITB attack need an iframe?

### ISSUE THREAD

**Issue by NDevTK** [odacavo/enhanced-iframe-protection#9]
The example used is "a phishing website has embedded an iframe element".
If the parent is attacker controlled then it would be possible to remove the warning or just not use an iframe such as by using an embed tag.

The detection code should also support dynamically created embeds
```
f = document.createElement('iframe');
f.src = 'https://example.org';
document.body.appendChild(f);
```
Seems that adding childList: true fixes this.

`document.URL` is attacker controlled using a html base tag.

Even if the parent is trusted the victim origin would need to not have any open redirects.

This extension could work for clickjacking protection but currently could not be trusted without using the webNavigation API and the Intersection Observer v2 API. To detect frames and allow the security UI to not be spoofed by attackers.

**Comment by MalwareCube** [comment]
Extension was built to detect https://github.com/mrd0x/BITB phishing page websites.

Feel free to submit a pull request to extend functionality.

**Comment by NDevTK** [comment]
But this extension is meant to "protect against Browser-In-The-Browser (BITB) attacks" this is detecting iframes a common thing for websites to do.

Seems this should detect fake security UI and I dont get why this would get closed so soon never claimed to not be providing a PR.

**Comment by NDevTK** [comment]
Explanation for closing this issue is at https://malware.is/writing/i-built-a-tool-to-defend-against-bitb-phishing-attacks
Started fake UI detection in #10 as I think iframes are to common to be a good way to fingerprint this attack template.
